- added nice priority tweaking - added ionice priority tweaking - some cleanups

diff --git a/usr/local/sbin/backup_all_guests b/usr/local/sbin/backup_all_guests
--- a/usr/local/sbin/backup_all_guests
+++ b/usr/local/sbin/backup_all_guests
@@ -110,7 +110,7 @@ then
 		echo "beende BACKUP-MANAGER:"
 		echo " "
 
-		$SNAPBACKUPUMNT $BDOM $BNAME $BVOL && echo "Domain unmounted" || echo "Domain umount ERROR!"
+		$CMD_FULLNICE $SNAPBACKUPUMNT $BDOM $BNAME $BVOL && echo "Domain unmounted" || echo "Domain umount ERROR!"
                 echo " ";
 		$BIN_DATE
 		echo " "
