v1.0a

diff --git a/usr/local/sbin/backup_all_guests b/usr/local/sbin/backup_all_guests
--- a/usr/local/sbin/backup_all_guests
+++ b/usr/local/sbin/backup_all_guests
@@ -1,42 +1,31 @@
 #!/bin/sh
 ########################################
-## MAIN Backup Script  
-## by Niels
-## (c) 2017 (GPLv2)
+## DO Snapbacks one by one
+## XEN DOMU LVM backup script
+## by Niels <nd@syndicat.com>
+## https://www.syndicat.com/
+## (c) 2015-2020 (GPLv2)
+## v1.0a
 ########################################
 
-SBCONFIGFILE="/etc/xenback_vols"
-SNAPBACKUPMNT="/usr/local/sbin/snaps_backup_mount"
-SNAPBACKUPUMNT="/usr/local/sbin/snaps_backup_umount"
-
-BACKUP_MANAGER="/usr/sbin/backup-manager"
-BACKUP_MANAGER_CONFIG="/etc/backup-manager.conf"
-
-# backup device
-BCKDEV="/dev/sdc5"
-
-# backup device filesystem (mount)
-BCKDEVMNTFS="ext4"
-
-# backup device mountpoint
-BCKMNTP="/backup/guests"
-
-# backup temp mount point (should be empty) 
-MNTSOURCEDIR="/4backup"
 
 
-#init
-#BM_TARBALL_DIRECTORIES=""
-#export BM_TARBALL_DIRECTORIES
-#TARBALL_DIRECTORY=""
-#export TARBALL_DIRECTORY
+XENBACK_CONF="/etc/xenbackup.conf"
+# read the config
+source $XENBACK_CONF
+
 
 echo ""
 echo "Mount BACKUP Device:"
 echo "===================="
 echo " "
-/bin/mount -t $BCKDEVMNTFS $BCKDEV $BCKMNTP && echo "done. " || echo "could NOT mount Backup Device (or still mounted) !" 
+$BIN_MOUNT -t $BCKDEV_FS $BCKDEV $BCKMNTP && echo "done. " || echo "could NOT mount Backup Device (or still mounted) !" 
+echo " "
+echo "space:"
+$BIN_DF -h $BCKMNTP
 
+# debug
+#exit
 
 echo " "
 echo "DO XEN SNAPBACKS"
@@ -51,11 +40,11 @@ do
 	TARBALL_DIRECTORY=""
 	export TARBALL_DIRECTORY
 
-	BDOM=$(/bin/echo $NAME | /usr/bin/cut -d '|' -f 1)
-	BNAME=$(/bin/echo $NAME |/usr/bin/cut -d '|' -f 2)
-	BVOL=$(/bin/echo $NAME | /usr/bin/cut -d '|' -f 3)
-	BFSTYPE=$(/bin/echo $NAME |/usr/bin/cut -d '|' -f 4)
-	BFOPTS=$(/bin/echo $NAME |/usr/bin/cut -d '|' -f 5)
+	BDOM=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 1)
+	BNAME=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 2)
+	BVOL=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 3)
+	BFSTYPE=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 4)
+	BFOPTS=$($BIN_ECHO $NAME | $BIN_CUT -d '|' -f 5)
 
 
 	if [ -n "$BFOPTS" ]; then
@@ -91,17 +80,17 @@ do
 		echo " "
 		echo "sichere Directories: $BM_TARBALL_DIRECTORIES"
 		echo " "
-		/bin/date
+		$BIN_DATE
 		echo " "
 		echo "starte BACKUP-MANAGER:"
-		$BACKUP_MANAGER -v -c $BACKUP_MANAGER_CONFIG
+		$BIN_BACKUPMAN -v -c $BM_CONFIGFILE
 		echo " "
 		echo "beende BACKUP-MANAGER:"
 		echo " "
 
 		$SNAPBACKUPUMNT $BDOM $BNAME $BVOL $BFSTYPE $BFOPTS && echo "Domain unmounted" || echo "Domain umount ERROR!"
                 echo " ";
-		/bin/date
+		$BIN_DATE
 		echo " "
 
         fi
@@ -112,4 +101,4 @@ echo ""
 echo "UNmount BACKUP Device:"
 echo "===================="
 echo " "
-/bin/umount $BCKMNTP && echo "done. " || echo "could NOT unmount Backup Device (possibly still mounted) !"
+$BIN_UMOUNT $BCKMNTP && echo "done. " || echo "could NOT unmount Backup Device (possibly still mounted) !"
